### ISSUE TITLE
Channel list is empty

### ISSUE THREAD

**Issue by rikardfalkeborn** [kodi-svtplay/xbmc-svtplay#150]
Seems channels (Kanaler) does not work anymore, I get an empty list.

Steps to reproduce:
1. Click channels (Kanaler)
2. List is empty, instead showing Svt1, Svt2, etc.

I'm using Osmc, on a Raspberry Pi. There are nothing in the log that suggests something went wrong.

**Comment by linqcan** [comment]
Site change by SVT. Lots of tests are failing now. Need to make a long term solution..

**Comment by linqcan** [comment]
I am currently fixing everything that broke after the new CMS was put in place by SVT.
Some commits have been submitted but they might be invalidated soon by a new solution that I am working on. Since it is a bit messy and I want to get it right (less hacky parsing) it might take some time to fix this. I'd refer you all to the web/android/ios applications until then.

**Comment by linqcan** [comment]
Note, channels should work if you download latest source code version from GitHub.
Haven't pushed to XBMC/Kodi yet due to some other patches needed as well.

**Comment by linqcan** [comment]
Fixed by dff4b5cb86f003ebac458407a7ac3b06a4e94801
