### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by ptryk** [kodi-svtplay/xbmc-svtplay#163]
when video plays we are experiencing a loss of connection to hdmi whereby when hdmi restarts the video has progressed.. not sure if it could be related to this plugin or the pi or system (osmc)... log from osmc including debug is here
http://paste.osmc.io/cipusovoru

**Comment by linqcan** [comment]
The plug-in only serves URLs to Kodi. If you are having that kind of severe
playback issues you should refer to your distribution's support channels.
I.e, this is most likely not a plug-in issue.

The plug-in serves HLS streams to Kodi. In your case it it ffmpeg that is
doing the decoding and playback. This information might be of use in your
troubleshooting.

Also, please note that only Kodi is the supported distribution/platform by
the plug-in. All other variants are unsupported due to reasons.
