### ISSUE TITLE
Seasons not displaying

### ISSUE THREAD

**Issue by spiffzilla** [kodi-svtplay/xbmc-svtplay#169]
When browsing a tv show with seasons (example http://www.svtplay.se/bron?tab=sasong3) the episode list is showing
"Episode 1"
"Episode 1"
"Episode 1"
"Episode 2"
"Episode 2"
"Episode 2"
....
...
..

No indication per episode wich seasong it belong to, making watching a series difficult
(Runninbg newest Kodi on RPi)

**Comment by linqcan** [comment]
Lots of things are broken due to site changes. I am currently looking into
this.

**Comment by linqcan** [comment]
Christmas came early this year. I've added "S?E?" information. Hope that helps!

Version 4.0.35 has been submitted to Kodi and they will push it when they are ready.
https://github.com/xbmc/repo-plugins/pull/763

**Comment by spiffzilla** [comment]
Woohooo..  Thanks

**Comment by asplundj** [comment]
The episodes are now named
Avsnitt 1 (S1E1) meaning that when you sort them alphabetically you will get

Avsnitt 1 (S1E1)
Avsnitt 1 (S2E1)
Avsnitt 1 (S3E1)

If you instead start with (S1E1) Avsnitt 1 you will be able to sort by season and then episode which makes much more sense. Also, it would be nice with a zero before 1-9 otherwise episode ten will be sorted after 1 instead of after 9.

**Comment by linqcan** [comment]
@asplundj The information is taken from the show info. I'm sorry to say but I won't modify the data as it would give us a lot of maintenance for little value (my opinoin).
