### ISSUE TITLE
Missing sort by option/bad sorting in "rapport" program list

### ISSUE THREAD

**Issue by EdvinAblad** [kodi-svtplay/xbmc-svtplay#216]
Don't know if this is a bug or a missing feature but it would be very useful to have the "sort by" option when browsing.

For example when looking into the program "Rapport" the result seems to be shuffled... So finding the latest rapport in that list is quite cumbersome. 

A solution to this would be to be able to sort the list (as you do when browsing your own media library on kodi) on e.g. title (or if possible aired date).  

(It seems to exist an old feature branch including this as mentioned in #127 )

**Comment by linqcan** [comment]
Sorting is a bit of a mess and requires some internal knowledge to get it working properly for shows like Rapport and Aktuellt. I have skipped this on purpose in order to make the plugin more maintainable (i.e keeping the one-off hacks as few as possible) and the current sorting (no sorting) works for almost every other show.
However, I agree that the Rapport listing is confusing and I spent some time researching how "they" do sorting. I will report back here whenever I come to a decision wether it is worth adding or not.

**Comment by EdvinAblad** [comment]
Good point.
A suggested (simple) solution, would be to add below code in addDirectoryItem. Thus the default method is to keep the sorting given from SVT, but the user can switch to alphabetic if they want. (switching back requires reload which can be considered a downside)...
`  xbmcplugin.addSortMethod(PLUGIN_HANDLE, xbmcplugin.SORT_METHOD_UNSORTED)
  xbmcplugin.addSortMethod(PLUGIN_HANDLE, xbmcplugin.SORT_METHOD_LABEL)`

Do what you want with this input =)

**Comment by linqcan** [comment]
Thanks for the suggestions!
I prefer this way as no extra magic is needed.

I added the options and made a new version available for Kodi to pull in. Whenever they pull it in it should appear for you. Try the setting out and let me know how it works!

https://github.com/xbmc/repo-plugins/pull/1488
