### ISSUE TITLE
Hide certain shows from techsavvy kids

### ISSUE THREAD

**Issue by RevJesseCuster** [kodi-svtplay/xbmc-svtplay#221]
# Steps to reproduce

Would be nice if you could hide or pinprotect certain shows not appropriate for smaller children.
# System information
Kodi version: 

Platform: 

Plugin version: 

# Log

#

**Comment by linqcan** [comment]
The addon has sort of gone the other way. Functionality has been removed in order to simplify maintenance. Not saying it will never happen, but it is not likely.

However, to have all information if this feature is considered. How would you imagine it working? Could you please describe step by step how you imagine the feature? Thanks!

**Comment by linqcan** [comment]
Hi @RevJesseCuster , a future release will contain a simple version of this based on the classification already done by SVT. The addon will have a setting which, when turned on, will hide content "inappropriate for children".
