### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by asplundj** [kodi-svtplay/xbmc-svtplay#224]
Currently "Categories" shows all genres listed at https://www.svtplay.se/genre. These are basically just key-words with various level of precision. For instance we have the gategory "drama" which makes sense but we also have 7 different categories starting with "Fler perspektiv". There's whole bunch of different categories for sports. Basically every sport has its own category.
This makes the is super long making it hard to find what you are looking for.

Would it be possible to just list the 12 categories from svtplay.se (Drama, Dokumentär, Humor, Barn, Nyheter, Sport. Livsstil, Underhållning, Musik, Kultur, Samhälle&Fakta and Öppet arkiv). Ideally these categories should have the images from svtplay.se

Perhaps the full list of genres could be listed separately.

**Comment by linqcan** [comment]
The 12 genres listed on https://www.svtplay.se/program are hard coded.
In order to lower maintenance for this addon I removed the hard coding in the addon and instead the complete list is shown. **Currently** I think the value of having low maintenace is higher than the value you are describing. However, this analyze could change with time.

In the meanwhile I offer this remedy; If you are using Kodi with a keyboard you could search/jump to menu items by doing Shift+"first letter in genre". For example, if you want to jump to "Drama" and/or "Dokumentär" you hit Shift+D. See https://kodi.wiki/view/Keyboard_controls for more keyboard shortcuts.
