### ISSUE TITLE
Hide shows that are not available yet

### ISSUE THREAD

**Issue by linqcan** [kodi-svtplay/xbmc-svtplay#226]
2019-01-26: There is a "validFrom" prop with TZ info that can be used to see if a show is available yet or not.

Suggestion from the following PR: https://github.com/nilzen/xbmc-svtplay/pull/225

**Comment by linqcan** [comment]
@Liffon Svt changed their API to deliver time zone aware dates, so this functionality can now be done without any weird parsing.

I have the feature on branch, but I am not sure how useful it is (worth merging).
https://github.com/linqcan/xbmc-svtplay/tree/krypton-hide-not-yet-playable

Do you have any examples of where this is useful?

**Comment by Liffon** [comment]
That parsing does seem very much more sane! Nice to have better inputs from the API.

For me, the use case was that when viewing the list of episodes for certain shows, some of the episodes would not play when I tried to select them. After a bit of digging I discovered that some episodes did not have any available content because they had not yet been published. In my mind it was more or less a bug that these episodes were visible, since there was no way of playing them.

Maybe an even better solution would be to show all the episodes, but make it clear to the user that they are not selectable for playback. I don't know if it's possible to display items as disabled in Kodi, but that seems like it would be a reasonable way of doing it in that case. (And if it's configurable, I think I would prefer having the hiding enabled by default.)

It was a while since I used either Kodi or this plugin, but if it's still the case that unplayable episodes are still visible in SVT's feed, then it sounds very useful. I remember that it was quite frustrating having my daughter choose an episode of her favourite show only to have nothing happen when it was selected.

**Comment by linqcan** [comment]
@Liffon Thanks for replying!

With the new API I have chosen not to scrape "Kommande" (not available shows) so by that this issue should be able to but in once case; search.

Based on your input I think it is better to scrap the setting and always hide not available (for search etc) since the addon is implicitly doing it already.

**Comment by Liffon** [comment]
Hey, thanks for asking for my input, it's fun to contribute to something every now and then :)

It sounds like you have a more proper solution in place compared to the one I hacked together. Nice!

**Comment by linqcan** [comment]
Turns out items in "Kommande" does not show up when searching, so this feature is not needed at all.

Will keep the feature branch in case it is needed in the future but not merge. Closing this issue now.

https://github.com/linqcan/xbmc-svtplay/tree/krypton-hide-not-yet-playable
