### ISSUE TITLE
 Kodi 18.2 ERROR: InputStream: Error

### ISSUE THREAD

**Issue by payano** [kodi-svtplay/xbmc-svtplay#228]
# Problem description
When trying to play from a "channel" from channels, i get this error message: 
2019-03-12 21:18:47.756 T:2518676320   ERROR: InputStream: Error opening, plugin://plugin.video.svtplay/?url=ch-svt24&mode=video
And shortly after, Kodi crashes

# Steps to reproduce
Running Kodi 18.2 in an Odroid XU4, install guide is here: https://forum.odroid.com/viewtopic.php?f=98&t=34149
Going and playing a channel from the channels category makes kodi crash.

# System information
Kodi version: 18.2

Platform:  Ubuntu (Odroid XU4)

Plugin version:  Latest (installed 2019-03-12)

# Log
https://paste.ubuntu.com/p/MMbmXnjJkp/

**Comment by linqcan** [comment]
I'd suspect this is platform related. Please open an issue with the Odroid community instead.

I tried on Kodi 18.1 on Android (from GPS, offfical Kodi build) and cannot reproduce. 

Also, are you running 18.2? Latest version is 18.1, if you are running a future version (beta etc) your milage may vary...

Will close, for now, as not caused by this addon.
