### ISSUE TITLE
Main titles missing

### ISSUE THREAD

**Issue by andreas1974** [kodi-svtplay/xbmc-svtplay#288]
After the latest update to accomodade for changes in the SVT API (xbmc-svtplay ver 5.1.18) there is a slight problem with program names in the lists, and in the information. It seems the main titles are missing, so for many programs it just says like "avsnitt 2" and the main title e.g. "Fröken Friman" is not present.

![Capture](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/12889ba5-22e4-44c8-aa54-056c2da87913)

There are also a lot of shorter clips that perhaps have no main title on SVT either, and for them the descriptions in the Kodi lists perhaps work well ... This one: https://www.svt.se/nyheter/utrikes/unikt-fynd-i-okengrotta-fyra-romerska-svard has a name in the Kodi plugin such as "1000 år gamla svärd" ... I don't know what main title they ought to be for clips like that. Other clips have just the time (such as 07:30) for name.

**Comment by linqcan** [comment]
Thanks for reporting this!
I must have mapped it wrong somehow.

**Comment by linqcan** [comment]
@andreas1974 I have looked at this now. Are you sure there is a change since 5.1.19? It seems like I can't really control this label in a good way. The only way to get the TvShow name there too is by having every row in the previous list be something like "SHOWNAME - EPISODENAME", which I don't want as it gets very repetitative.

I found a lot of other issues though with titles and metadata, so thanks for making me look! :-)

**Comment by dobbelina** [comment]
When i click "Latest programs" description seems to have been replaced with heading.
See the 3 illustrative screenshots below:
![image](https://github.com/kodi-svtplay/xbmc-svtplay/assets/46063764/6a16f8d7-7789-4a09-a1b2-260ea71f5bfe)
And
![image](https://github.com/kodi-svtplay/xbmc-svtplay/assets/46063764/6d28ef94-4ff7-40a6-b080-46351311162f)
And
![image](https://github.com/kodi-svtplay/xbmc-svtplay/assets/46063764/062b2e3a-e5fe-4f83-aa3e-daa377a057d1)

**Comment by linqcan** [comment]
Thanks for reporting!
These issues have been identified and a v5.1.20 is on its way out with a fix for this.

**Comment by andreas1974** [comment]
@linqcan 
> "Are you sure there is a change since 5.1.19? It seems like I can't really control this label in a good way. "

No... I'm not perfectly sure. Could it be that SVT are not consistent in the data? Since some "shows" have their main title written out, and others have just the "time" (lacking a main title altogether). 
I'm looking forward to the new version and **you may very well have detected and fixed everything that can be easily fixed. Then just disregard my ramblings below!**

Were you referring to the "pause screen" on my previous screen shot? I just took for granted it was a problem in _the listings_ and also in the _pause screen_, since it says "Avsnitt 2" twice on both places, and no main title at all. And there seems to be a main title when I use a web browser.

Here is another example (I expected to see "Uutiset" on all the places I've circled in red, and "17:45" in the places circled in blue):
![tv-bild från listan](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/2f2895fd-1af9-4041-ab59-bec2625d8f00)

![Senaste Uutiset 1745 Pause screen](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/be5ee007-93df-4044-8445-e8408cf66cd4)

Here is what the same title looks like in my browser:
![Senaste Uutiset 1745](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/90071595-690c-4c80-8901-99621e869640)

**Comment by linqcan** [comment]
> @linqcan
> 
> > "Are you sure there is a change since 5.1.19? It seems like I can't really control this label in a good way. "
> 
> No... I'm not perfectly sure. Could it be that SVT are not consistent in the data? Since some "shows" have their main title written out, and others have just the "time" (lacking a main title altogether). I'm looking forward to the new version and **you may very well have detected and fixed everything that can be easily fixed. Then just disregard my ramblings below!**
> 
This has nothing to do with the data source. This has to do what the title is of the list item that is played. For episodes in a program listing I have intentionally omitted to write out the program name on every list item as it gets really repetitive and cluttered in the UI. Also, it is assumed that you know what program you were trying to watch. 

However, there was a bug in mixed listings such as popular and latest programs, where only the episode name was shown and not the program name. This is fixed in 5.1.20. Additionally, "Popular" contains programs as list items in the data source and not episodes. Hence they now, since 5.1.20, directs you to the program's episode listing. 

I hope this explains some of what you are seeing. 5.1.20 should roll out to Kodi 19 and higher now and will come to lower versions as soon as it has been accepted by Kodi for those versions.

**Comment by linqcan** [comment]
@andreas1974 let me know if 5.1.20 does not solve the listing issues you were seeing.

**Comment by andreas1974** [comment]
Thanks! I'm looking forward to the rollout for older versions (I'm on Kodi 18.9).

**Comment by linqcan** [comment]
> Thanks! I'm looking forward to the rollout for older versions (I'm on Kodi 18.9).

It should already be live.

The addon can be seen for krypton and above here
https://mirrors.kodi.tv/addons/krypton/plugin.video.svtplay/
Make you have auto update available.

**Comment by andreas1974** [comment]
Sorry, I didn't check today, and yesterday evening it was still 5.1.19. 
Now the main titels show up! Great!

There is one problem left, but I believe it may be an old one, even if it relates to the information pane for any program. I just didn't realize until today why program information (pressing the "(i)" symbol) is sometimes missing. Now I see it's just when I start a program from the favourites menu in Kodi. Also that is when "Resume" does not work. **I'll add a new issue about this.**
