### ISSUE TITLE
Exception playing Öppet arkiv

### ISSUE THREAD

**Issue by kokangit** [kodi-svtplay/xbmc-svtplay#47]
Choosing Kategorier/Öppet arkiv/Lasermannen renders an exception:

  File "/home/mgu/projekt/xbmc-svtplay/default.py", line 697, in <module>
    viewProgram(url,page,index)
  File "/home/mgu/projekt/xbmc-svtplay/default.py", line 187, in viewProgram
    createDirectory(url,page,index,MODE_PROGRAM,MODE_VIDEO)
  File "/home/mgu/projekt/xbmc-svtplay/default.py", line 299, in createDirectory
    populateDirNoPaging(url,dirtype,tabname)
  File "/home/mgu/projekt/xbmc-svtplay/default.py", line 393, in populateDirNoPaging
    articles = getArticles(url,None,tabname)
  File "/home/mgu/projekt/xbmc-svtplay/default.py", line 447, in getArticles
    attrs = { "data-tabname": tabname })[0]
IndexError: list index out of range

**Comment by linqcan** [comment]
It's because we assume that a program listed in "Kategorier" always contains a tab named "episodes". In this case (and maybe others) the program does not contain that tab but only a "clips" tab.

We should probably use the same method as we do with search where we look for all tabs. Will look into it!

As a workaround you could search for "lasermannen" using the "Search" feature and you will be able to access the clips from there.

Sources:
http://www.svtplay.se/lasermannen
http://www.svtplay.se/sok?q=lasermannen

**Comment by linqcan** [comment]
I've got a test version working. Will polish the code a bit and publish a PR for you to test in the upcoming days.

The PR will introduce a new behavior: All programs will have an extra level of navigation listing "Episodes" and "Clips" (if any). More clicking, is it worth it? (Probably since you can access all content now :) )

**Comment by linqcan** [comment]
PR #48 is now up for review/test.
