### ISSUE TITLE
Can't fast forward or drag and drop time when playing homeland

### ISSUE THREAD

**Issue by prinzhen** [kodi-svtplay/xbmc-svtplay#55]
Can't fast forward or drag and drop timeindicatorr when playing Homeland on svtplay. Homeland video playing in SD resolution. I cant get it playing in 720, all other programs playing in 720 and in those I can fast forward video and drag and drop timeindicator.

**Comment by linqcan** [comment]
Judging from the source, Homeland is provided in Flash format only (not HLS) which would explain why you can't fast-forward. Moreover, the format of the stream information is new to me and therefore the parser will not be able not pick any other stream than the SD version (320kbit/s). Will see if the parser can be improved to handle this and related cases.

**Comment by linqcan** [comment]
I made an updated parser which you can find in my repo below. I have tested the code offline but I can't test it in XBMC since I don't have XBMC available at the moment. If you have time and would like to test it I would be more than happy. 
Download the zip through GitHub and install it using "Install from zip" in XBMC's addon settings.

https://github.com/linqcan/xbmc-svtplay/tree/newparser

**Comment by linqcan** [comment]
This is now PR #56
